name: Nix

on:
  push:
    paths:
      - flake.nix
      - flake.lock
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/nix.yml
  pull_request:
    paths:
      - flake.nix
      - flake.lock
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/nix.yml
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Build and test
        run: nix build -L --no-update-lock-file
      - name: Run
        run: nix run . -- --version
